<selection class="content">
    <?php if(isset($data['params']['success']) && $data['params']['success']) { ?>
        <div class="alert alert-success">
                Ação Realizada com Sucesso!
        </div>
    <?php } ?>
    <?php if(isset($data['params']['error']) && $data['params']['error']) {?>
        <div class="alert alert-danger">
            <?= $data['params']['error']; ?>
        </div>
    <?php } ?>    
    <div class="box box-primary">
        <div class="box-header with-border">
            <h4><i class="glyphicon glyphicon-edit"></i> Filtros de busca de produtos</h4>
        </div>
        <form method="post" enctype="multipart/form-data" id="produto-index" action="/produtos" role="form" class="form-vertical">
            <div class="box-body">
                <div class="box-body">
                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label>ID Produto </label>
                            <input type="text" name="id" id="id"  class="form-control"  pattern="{0}" value="<?= $data['params']['id'] ?? ''?>">
                        </div>
                        <div class="form-group col-sm-6">
                            <label>Descrição do Produto </label>
                            <input type="text" name="descricao" id="descricao"  class="form-control"  pattern="{0}" value="<?= $data['params']['descricao'] ?? ''?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="pull-right">
                    <input type="submit" name="submit" id="submit" class="btn btn-primary" style="margin-right: 5px;" onclick="" value="Buscar">        
                </div>
            </div>
        </form>
    </div>
    <div class="box box-warning">
        <div class="box-header">
            <div class="pull-left">
                <h3 class="box-title">Foram encontrados <b><?= $data['total_items']; ?></b> resultados.</h3>
            </div>
            <p class="pull-right">
                <a id="" style="margin-left: 5px;" title="Novo" href="/produtos/save" class="btn btn-warning"><i class="fa fa-save"></i> Novo</a>        
            </p>
        </div>
        <div class="box-body">
            <div class="box-body table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                        <tr class="thead-font">
                            <th> Ações</th>
                            <th> Id</th>
                            <th> Descrição</th>
                            <th> Valor</th>
                            <th>Quantidade Estoque</th>
                            <th>Cadastrado Em</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($data['produtos'] as $produto) { ?>    
                        <tr class="tbody-font">
                            <td>
                                <a target="_blank" id="" style="margin-left: 5px;" title="Editar" href="/produtos/save?id= <?= $produto['id'] ?>" class="btn btn-success btn-md"><i class="glyphicon glyphicon-edit"></i></a>
                                <a id="" style="margin-left: 5px;" title="Excluir" href="#" onclick="confirmModal('Você confirma a exclusão?', '/produtos/delete?id=<?= $produto['id'] ?>'); return false;" class="btn btn-danger btn-md"><i class="glyphicon glyphicon-trash"></i></a>                        
                            </td>
                            <td><span class="label label-success"><?= $produto['id']; ?></span></td>
                            <td><?= $produto['descricao']; ?></td>
                            <td><?= $produto['valor']; ?></td>
                            <td><?= $produto['estoque']; ?></td>
                            <td><?= $produto['created_at']; ?></td>
                        </tr>
                    <?php } ?>    
                    </tbody>
                </table>
                <?php 
                    require_once __DIR__.'/../../../Core/view/paginate.phtml'; 
                ?>
            </div>
        </div>
    </div>
</selection>