<?php if(isset($data['error']) && $data['error']) {?>
   <div class="alert alert-danger">
      <?= $data['error']; ?>
   </div>
<?php } ?>
<section class="content">
   <div class="box box-success">
      <div class="box-header with-border">
         <h3 class="box-title"><i class="glyphicon glyphicon-edit"></i> Cadastrar Produto</h3>
      </div>
      <form method="post" enctype="multipart/form-data" id="produto-save" action="/produtos/save" role="form">
         <input type="hidden" name="id" id="id"  value="<?= $data['produto']['id'] ?? ""; ?>">
         <div class="box-body">
            <div class="row">
                <div class="form-group col-sm-8">
                    <label>Descrição<span style="color: red;"> *</span></label>
                    <input type="text" name="descricao" required="required" id="descricao" placeholder="Descrição" class="form-control"  value="<?= $data['produto']['descricao'] ?? ''; ?>">
                </div>
                
            </div>
            <div class="row">
                <div class="form-group col-sm-4">
                    <label>Valor de Venda<span style="color: red;"> *</span></label>
                    <input type="text" name="valor" required="required" id="valor" placeholder="Valor de Venda" class="form-control real"  value="<?= $data['produto']['valor'] ?? ''; ?>">
                </div>
                <div class="form-group col-sm-4">
                    <label>Quantidade no Estoque<span style="color: red;"> *</span></label>
                    <input type="number"   max="999"  name="estoque" required="required" id="estoque" placeholder="Quantidade no estoque" class="form-control"  value="<?= $data['produto']['estoque'] ?? ''; ?>">
                </div>
            </div>
         </div>   
         <div class="box-footer">
            <div class="margin">
               <button type="submit" name="submit" id="submit" class="btn btn-success" style="margin-right: 5px;" value="Salvar">Salvar</button>
               <button type="button" name="cancel" id="cancel" class="btn btn-danger btn-xl" style="margin-right: 5px;" onclick="confirmRedirectModal('Deseja realmente sair? ', '/produtos'); return false;" value="">Sair</button>        
            </div>
         </div>
      </form>
   </div>

   <?php if(isset($data['produto']['id']) && $data['produto']['id']) { ?>
      <div class="box box-warning">
         <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-camera"></i> Fotos do Produto</h3>
         </div>
         <div class="box-body">
            <a type="button" name="adicionar" id="adicionar" class="btn btn-primary btn-xl" style="margin-right: 5px;" href="/arquivos-de-produtos/save?id=<?= $data['produto']['id'] ?>" value="">
               <i class="fa fa-upload" style="margin-right:5px;"> </i> Adicionar Novas Fotos
            </a>        
         </div>
      </div>
   <?php } ?>   
   <script type="text/javascript">
        $(document).ready(function () {
            $(".real").mask('00.000.000,00', {reverse: true}); 
        });      
   </script>
</section>