<selection class="content">
    <?php if(isset($data['params']['success']) && $data['params']['success']) { ?>
        <div class="alert alert-success">
                Ação Realizada com Sucesso!
        </div>
    <?php } ?>    
    <div class="box box-primary">
        <div class="box-header with-border">
            <h4><i class="glyphicon glyphicon-edit"></i> Filtros de busca de pedidos</h4>
        </div>
        <form method="post" enctype="multipart/form-data" id="pedido-index" action="/pedidos" role="form" class="form-vertical">
            <div class="box-body">
                <div class="box-body">
                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label>ID Pedido </label>
                            <input type="text" name="id" id="id"  class="form-control"  pattern="{0}" value="<?= $data['params']['id'] ?? ''?>">
                        </div>
                        <div class="form-group col-sm-6">
                            <label>Descrição do Pedido </label>
                            <input type="text" name="descricao_pedido" id="descricao_pedido"  class="form-control"  pattern="{0}" value="<?= $data['params']['descricao_pedido'] ?? ''?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="pull-right">
                    <input type="submit" name="submit" id="submit" class="btn btn-primary" style="margin-right: 5px;" onclick="" value="Buscar">        
                </div>
            </div>
        </form>
    </div>
    <div class="box box-warning">
        <div class="box-header">
            <div class="pull-left">
                <h3 class="box-title">Foram encontrados <b><?= $data['total_items']; ?></b> resultados.</h3>
            </div>
            <p class="pull-right">
                <a id="" style="margin-left: 5px;" title="Novo" href="/pedidos/save" class="btn btn-warning"><i class="fa fa-save"></i> Novo</a>        
            </p>
        </div>
        <div class="box-body">
            <div class="box-body table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                        <tr class="thead-font">
                            <th> Ações</th>
                            <th> Id</th>
                            <th> Descrição</th>
                            <th> Nome Comprador</th>
                            <th> Valor Total</th>
                            <th> Data do Pedido</th>
                            <th> Pedido Finalizado</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($data['pedidos'] as $pedido) { ?>    
                        <tr class="tbody-font">
                            <td>
                                <?php if($pedido['pedido_finalizado'] == '0'){ ?>
                                    <a target="_blank" id="" style="margin-left: 5px;" title="Editar" href="/pedidos/save?id= <?= $pedido['id'] ?>" class="btn btn-success btn-md"><i class="glyphicon glyphicon-edit"></i></a>
                                <?php } ?>
                                <a id="" style="margin-left: 5px;" title="Excluir" href="#" onclick="confirmModal('Você confirma a exclusão?', '/pedidos/delete?id=<?= $pedido['id'] ?>'); return false;" class="btn btn-danger btn-md"><i class="glyphicon glyphicon-trash"></i></a>                        
                            </td>
                            <td><span class="label label-success"><?= $pedido['id']; ?></span></td>
                            <td><?= $pedido['descricao_pedido']; ?></td>
                            <td><?= $pedido['nome_comprador']; ?></td>
                            <td><?= $pedido['valor_total_pedido'] ?? "0,00"; ?></td>
                            <td><?= $pedido['created_at']; ?></td>
                            <td><?= $pedido['pedido_finalizado'] ? "Sim" : "Não"; ?></td>
                        </tr>
                    <?php } ?>    
                    </tbody>
                </table>
                <?php 
                    require_once __DIR__.'/../../../Core/view/paginate.phtml'; 
                ?>
            </div>
        </div>
    </div>
</selection>