<?php if(isset($data['error']) && $data['error']) {?>
   <div class="alert alert-danger">
      <?= $data['error']; ?>
   </div>
<?php } ?>
<?php if(isset($data['params']['success']) && $data['params']['success']) { ?>
      <div class="alert alert-success">
             Ação Realizada com Sucesso!
      </div>
<?php } ?>   
<section class="content">
   <div class="box box-warning">
      <div class="box-header with-border">
         <h3 class="box-title"><i class="glyphicon glyphicon-edit"></i> Salvar Pedido</h3>
      </div>
      <form method="post" enctype="multipart/form-data" id="pedido-save" action="/pedidos/save" role="form">
         <input type="hidden" name="id" id="id"  value="<?= $data['pedido']['id'] ?? ""; ?>">
         <div class="box-body">
            <div class="row">
                <div class="form-group col-sm-8">
                    <label>Descrição<span style="color: red;"> *</span></label>
                    <input type="text" name="descricao_pedido" required="required" id="descricao_pedido" placeholder="Descrição" class="form-control"  value="<?= $data['pedido']['descricao_pedido'] ?? ''; ?>">
                </div>
            </div>
            <div class="row">
               <div class="form-group col-sm-4">
                    <label>Nome Comprador </label>
                    <input type="text" name="nome_comprador" id="nome_comprador" placeholder="Nome Comprador" class="form-control"  value="<?= $data['pedido']['nome_comprador'] ?? ''; ?>">
                </div>
                <div class="form-group col-sm-4">
                    <label>CPF Comprador </label>
                    <input type="text" name="cpf_comprador" id="cpf_comprador" placeholder="CPF Comprador" class="form-control cpf"  value="<?= $data['pedido']['cpf_comprador'] ?? ''; ?>">
                </div>
            </div>  
         </div>   
         <div class="box-footer">
            <div class="margin">
               <button type="submit" name="submit" id="submit" class="btn btn-success" style="margin-right: 5px;" value="Salvar">Salvar</button>
               <button type="button" name="cancel" id="cancel" class="btn btn-danger btn-xl" style="margin-right: 5px;" onclick="confirmRedirectModal('Deseja realmente sair? ', '/pedidos'); return false;" value="">Sair</button>        
            </div>
         </div>
      </form>
   </div>

  
   <script type="text/javascript">
      $(document).ready(function () {
         $(".cpf").mask('000.000.000-00', {reverse: true}); 
      });
      
   </script>
</section>